name: Daily Job

on:
  schedule:
    - cron: "45 8 * * *"  # runs at 2:15 PM IST daily
  workflow_dispatch:      # lets you run it manually too

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
      - name: Run script
        run: python etl_pipeline.py
